export const songs = [
  {
    id: 0,
    title: '',
    artist: '',
    artwork: '',
    url: '',
  },
  {
    id: 1,
    title: 'song 1',
    artist: 'xyz',
    artwork: require('./imgSongs/img1.jpg'),
    url: require('./songs/msc1.mp3'),
  },
  {
    id: 2,
    title: 'song 2',
    artist: 'xyz',
    artwork: require('./imgSongs/img2.jpg'),
    url: require('./songs/msc2.mp3'),
  },
  {
    id: 3,
    title: 'song 3',
    artist: 'xyz',
    artwork: require('./imgSongs/img3.jpg'),
    url: require('./songs/msc3.mp3'),
  },
  {
    id: 4,
    title: 'song 4',
    artist: 'xyz',
    artwork: require('./imgSongs/img4.jpg'),
    url: require('./songs/msc4.mp3'),
  },
  {
    id: 5,
    title: 'song 5',
    artist: 'xyz',
    artwork: require('./imgSongs/img5.jpg'),
    url: require('./songs/msc5.mp3'),
  },
  {
    id: 6,
    title: 'song 6',
    artist: 'xyz',
    artwork: require('./imgSongs/img6.jpg'),
    url: require('./songs/msc6.mp3'),
  },
  {
    id: 7,
    title: 'song 7',
    artist: 'xyz',
    artwork: require('./imgSongs/img7.jpg'),
    url: require('./songs/msc7.mp3'),
  },
  {
    id: 8,
    title: 'song 8',
    artist: 'xyz',
    artwork: require('./imgSongs/img8.jpg'),
    url: require('./songs/msc8.mp3'),
  },
  {
    id: 9,
    title: 'song 9',
    artist: 'xyz',
    artwork: require('./imgSongs/img9.jpg'),
    url: require('./songs/msc9.mp3'),
  },
  {
    id: 10,
    title: 'song 10',
    artist: 'xyz',
    artwork: require('./imgSongs/img10.jpg'),
    url: require('./songs/msc10.mp3'),
  },
];
